{
 "title": "tidehunter-vultr",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Write rate(K/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(bench_writes_count[1m]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read rate(K/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(bench_reads_count[1m]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg write latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(bench_writes_sum[2m]) / rate(bench_writes_count[2m]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg read latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(bench_reads_sum[1m]) / rate(bench_reads_count[1m]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk writes Mb/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"md1\"}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read Mb/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"md1\"}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=\"md1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utl %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) / 48 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Large table lock contention (mcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(large_table_contention_sum[1m]) / rate(large_table_contention_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wal lock contention (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(wal_contention_sum[1m]) / rate(wal_contention_count[1m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending flushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "flush_pending", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage (Gb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{host=~\"^benchmark.*\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded keys (M)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "loaded_keys / 1024 / 1024", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lookup results(K)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "rate(lookup_result[1m]) / 1024", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wal written bytes by type(Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(wal_written_bytes_type[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entry state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "entry_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Read Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "benchmark_param_read_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zipf Exponent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_zipf_exponent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Write Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_write_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mixed Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_mixed_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Write Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_write_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Direct IO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_direct_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_operations", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_writes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Background Writes/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "benchmark_param_background_writes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_key_len", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Flusher Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "benchmark_param_num_flusher_threads",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fragment Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_frag_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Maps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_max_maps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Dirty Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "benchmark_param_max_dirty_keys", "legendFormat": "__auto" }
   ]
  }
 ]
}