{
 "title": "Tidehunter",
 "time": { "from": "2025-02-08T06:41:28.817Z", "to": "2025-02-08T17:56:24.592Z" },
 "templating": {
  "list": [
   { "name": "network", "query": "private-testnet" },
   { "name": "validator", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(num_shared_obj_tx{network=\"$network\", host=~\"$validator\"}[5m]))",
     "legendFormat": "shared"
    },
    {
     "expr": "quantile(0.5, rate(total_transaction_effects{network=\"$network\", host=~\"$validator\"}[5m]) - rate(num_shared_obj_tx{network=\"$network\", host=~\"$validator\"}[5m]))",
     "legendFormat": "owned"
    }
   ]
  },
  {
   "title": "Settlement finality latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, tx_type) (rate(quorum_driver_settlement_finality_latency_bucket{network=\"$network\"}[5m])))",
     "legendFormat": "p50-{{tx_type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, tx_type) (rate(quorum_driver_settlement_finality_latency_bucket{network=\"$network\"}[5m])))",
     "legendFormat": "p95-{{tx_type}}"
    }
   ]
  },
  {
   "title": "Validator handler latency - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "clamp(quantile(0.67, histogram_quantile(0.5, sum by(le, host) (rate(grpc_request_latency_bucket{network=\"$network\", host=~\"$validator\", path=\"/sui.validator.Validator/Transaction\"}[5m])))), 0, 5)",
     "legendFormat": "handle_transaction"
    },
    {
     "expr": "clamp(quantile(0.67, histogram_quantile(0.5, sum by(le, host) (rate(grpc_request_latency_bucket{network=\"$network\", host=~\"$validator\", path=\"/sui.validator.Validator/CertifiedTransactionV2\"}[5m])))), 0, 10)",
     "legendFormat": "handle_certificate"
    }
   ]
  },
  {
   "title": "Validator handler latency - p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "clamp(quantile(0.67, histogram_quantile(0.9, sum by(le, host) (rate(grpc_request_latency_bucket{network=\"$network\", host=~\"$validator\", path=\"/sui.validator.Validator/Transaction\"}[5m])))), 0, 5)",
     "legendFormat": "handle_transaction"
    },
    {
     "expr": "clamp(quantile(0.67, histogram_quantile(0.9, sum by(le, host) (rate(grpc_request_latency_bucket{network=\"$network\", host=~\"$validator\", path=\"/sui.validator.Validator/CertifiedTransactionV2\"}[5m])))), 0, 10)",
     "legendFormat": "handle_certificate"
    }
   ]
  },
  {
   "title": "Validator host CPU utilization%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(host) (rate(node_cpu_seconds_total{network=\"$network\", host=~\"$validator\", mode!=\"idle\"}[5m])) / sum by(host) (rate(node_cpu_seconds_total{network=\"$network\", host=~\"$validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator host memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{role=\"validator\", network=\"$network\", status=\"active\", host=~\"$validator\"} - node_memory_MemFree_bytes{role=\"validator\", network=\"$network\", status=\"active\", host=~\"$validator\"} - (node_memory_Cached_bytes{role=\"validator\", network=\"$network\", status=\"active\", host=~\"$validator\"} + node_memory_Buffers_bytes{role=\"validator\", network=\"$network\", status=\"active\", host=~\"$validator\"} + node_memory_SReclaimable_bytes{role=\"validator\", network=\"$network\", status=\"active\", host=~\"$validator\"})) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator host disk read throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(host) (rate(node_disk_read_bytes_total{network=\"$network\", host=~\"$validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator host disk write throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(host) (rate(node_disk_written_bytes_total{network=\"$network\", host=~\"$validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg lookup latency(mcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg by (ks, type) (rate(lookup_mcs_sum{network=\"private-testnet\", role=\"validator\"}[5m]) / rate(lookup_mcs_count{network=\"private-testnet\", role=\"validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 lookup latency(mcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg by (ks, type) (histogram_quantile(0.9, rate(lookup_mcs_bucket{network=\"private-testnet\", role=\"validator\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded keys (millions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg by (ks) (loaded_keys{network=\"$network\", role=\"validator\"}) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk lookups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg by (ks, type) (rate(lookup_mcs_count{network=\"private-testnet\", role=\"validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Large table lock contantion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avg by (ks) (rate(large_table_contention_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock contention delay (mcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "avg by (ks) (rate(large_table_contention_sum[5m])) / avg by (ks) (rate(large_table_contention_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wal lock contention (mcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg(rate(wal_contention_sum[5m]) / rate(wal_contention_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wal writes by type (Mbs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "avg by (type) (rate(wal_written_bytes_type[5m])) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB operations rate (thousands)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "avg by (ks, op) (rate(db_op_count{network=\"private-testnet\", role=\"validator\"}[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Db operation time (mcs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "avg by (ks, op) (histogram_quantile(0.99, rate(db_op_bucket{network=\"private-testnet\", role=\"validator\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lookup results by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "avg by (ks, result, source) (rate(lookup_result{network=\"private-testnet\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lookups on disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "avg by (ks, result, source) (rate(lookup_result{network=\"private-testnet\", source!~\"bloom|lru\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flusher utilization (pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(flush_time_mcs{network=\"private-testnet\", role=\"validator\"}[5m]) / 1000 / 1000 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot written Kb/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "rate(snapshot_written_bytes{network=\"private-testnet\", role=\"validator\"}[5m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot force unloads /sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "avg by (ks) (rate(snapshot_force_unload{network=\"private-testnet\", role=\"validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wal sync lag (Gb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "clamp_min((wal_written_bytes{network=\"private-testnet\", role=\"validator\"}-wal_synced_position{network=\"private-testnet\", role=\"validator\"}) / 1024 / 1024 / 1024, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory estimates(Gb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "max by (ks, kind) (memory_estimate{network=\"private-testnet\", role=\"validator\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "sum(max by (ks, kind) (memory_estimate{network=\"private-testnet\", role=\"validator\"}) / 1024 / 1024 / 1024)",
     "legendFormat": "Estimates"
    },
    {
     "expr": "max by (ks) (value_cache_size{network=\"private-testnet\", role=\"validator\"} / 1024 / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending certificates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "transaction_manager_num_pending_certificates{role=\"validator\", network=\"private-testnet\"} > 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "current_epoch{network=\"private-testnet\", role=\"validator\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}